### ISSUE TITLE
'off' should cancel 'once' binding

### ISSUE THREAD

**Issue by 11111000000** [WebReflection/eddy#2]

**Comment by WebReflection** [comment]
this might end up as won't fix for various reasons but for the time being, and as work around, if you need to arbitrary cancel `.once` you should probably do it pragmatically via `.on` and `.off`

The only possible way I see now is to pollute the internal object with yet another array of `.once` attached listener but it doesn't feel right ... it's also some sort of edge case that you want to drop `.once` externally .. can you explain me how frequently you need that?

**Comment by 11111000000** [comment]
it's not so important, but I think we need to document that case in README. In code I use .on/.off instead already, it's ok

**Comment by WebReflection** [comment]
Fair enough, added here https://github.com/WebReflection/eddy#note-about-off-and-once and https://github.com/WebReflection/eddy#objectoncetype-handler-capture .

For now I'm flagging this as won't fix. Thanks for opening this though, I agree from an API point of view one would expect that to work. Will think about it.
